#!/usr/bin/env python3
# Get the input and output file list.
from argparse import ArgumentParser
parser = ArgumentParser(
    description = "Create an asset file from binary files",
)
parser.add_argument(
    "-o",
    dest = "output",
    help = "Output header file name",
    required = True)
parser.add_argument(
    "input",
    help  = "Input files",
    nargs = "+")
args = parser.parse_args()

# Create a header file from the input.
output = open(args.output, "w")
for i in args.input:
    import os.path
    i = os.path.normpath(i)

    n = ""
    head, tail = os.path.split(i)
    tail = os.path.splitext(tail)[0]

    while tail != "":
        if head == "":
            n = tail.upper() + n
        else:
            n = "_" + tail.upper() + n
        head, tail = os.path.split(head)

    output.write("const static _Alignas(8) unsigned char ")
    output.write(n)
    output.write("[] = [")

    f = open(i, "rb")
    b = f.read(1)
    c = 0
    while len(b) == 1:
        if c == 0:
            output.write("\n    ")

        s = "0x{:02x}, ".format(b[0])
        output.write(s)

        b = f.read(1)
        c += 1
        c %= 12

    output.write("\n];\n\n")
output.close()
