[Window]
Width  = 800
Height = 600
SwapchainMode = "Mailbox"

[Simulation]
PlaneWidth  = 200.0
PlaneHeight = 200.0

HorizontalGranularity = 200
VerticalGranularity   = 200

[Simulation.Herbivores]
Budget       = 4096
Individuals  = 1000
ViewRadius   = 1.0
Signature    = { Red = 0.0, Green = 0.5, Blue = 1.0 }
InitToRandom = true

[Simulation.Predators]
Budget      = 4096
Individuals = 100
ViewRadius  = 1.0
Signature   = { Red = 0.0, Green = 0.5, Blue = 1.0 }
InitToRandom = true